# this is where we can add the sql db information. 
version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: "postgresql"
    environment:
      - name=value
    volumes:
      - db-data:/demo

volumes:
  db-data: