# this is where we can add the sql db information. 
version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    logging:
          options:
            max-size: 10m
            max-file: "3"
    ports:
          - "5438:5432"
    volumes:
      - db-data:/demo

volumes:
  db-data:
