# this is where we can add the sql db information. 
version: '3'
services:

  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    logging:
          options:
            max-size: 10m
            max-file: "3"
    ports:
          - "5438:5432"
    volumes:
      - db-data:/demo

  backend:
    build:
      context: backend
      dockerfile: ./backend.dockerfile
    ports:
      - "8765:8765"
    depends_on: 
      - db

volumes:
  db-data:

